/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppJudgeModeRouteImport } from './routes/app.judge-mode'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppNegotiationsIndexRouteImport } from './routes/app.negotiations.index'
import { Route as AppNegotiationsIdRouteImport } from './routes/app.negotiations.$id'
import { Route as AppNegotiationsNewRouteImport } from './routes/app.negotiations.new'
import { Route as ApiPublicElevenlabsPostCallRouteImport } from './routes/api/public/elevenlabs/post-call'
import { Route as AppNegotiationsIdCallsRouteImport } from './routes/app.negotiations.$id.calls'
import { Route as AppNegotiationsIdControlRoomRouteImport } from './routes/app.negotiations.$id.control-room'
import { Route as AppNegotiationsIdEvidenceRouteImport } from './routes/app.negotiations.$id.evidence'
import { Route as AppNegotiationsIdIntakeRouteImport } from './routes/app.negotiations.$id.intake'
import { Route as AppNegotiationsIdIntegrityRouteImport } from './routes/app.negotiations.$id.integrity'
import { Route as AppNegotiationsIdNegotiateRouteImport } from './routes/app.negotiations.$id.negotiate'
import { Route as AppNegotiationsIdOverviewRouteImport } from './routes/app.negotiations.$id.overview'
import { Route as AppNegotiationsIdProvidersRouteImport } from './routes/app.negotiations.$id.providers'
import { Route as AppNegotiationsIdQuotesRouteImport } from './routes/app.negotiations.$id.quotes'
import { Route as AppNegotiationsIdReadinessRouteImport } from './routes/app.negotiations.$id.readiness'
import { Route as AppNegotiationsIdReportRouteImport } from './routes/app.negotiations.$id.report'
import { Route as AppNegotiationsIdSpecificationRouteImport } from './routes/app.negotiations.$id.specification'
import { Route as AppNegotiationsIdVoiceIntakeRouteImport } from './routes/app.negotiations.$id.voice-intake'
import { Route as ApiPublicElevenlabsIntakePostCallRouteImport } from './routes/api/public/elevenlabs/intake/post-call'
import { Route as ApiPublicElevenlabsToolsFinalizeCallOutcomeRouteImport } from './routes/api/public/elevenlabs/tools/finalize-call-outcome'
import { Route as ApiPublicElevenlabsToolsLoadCallContextRouteImport } from './routes/api/public/elevenlabs/tools/load-call-context'
import { Route as ApiPublicElevenlabsToolsSaveQuoteLineItemRouteImport } from './routes/api/public/elevenlabs/tools/save-quote-line-item'
import { Route as ApiPublicElevenlabsToolsSaveQuoteSnapshotRouteImport } from './routes/api/public/elevenlabs/tools/save-quote-snapshot'
import { Route as ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRouteImport } from './routes/api/public/elevenlabs/intake/tools/finalize-intake-session'
import { Route as ApiPublicElevenlabsIntakeToolsLoadIntakeContextRouteImport } from './routes/api/public/elevenlabs/intake/tools/load-intake-context'
import { Route as ApiPublicElevenlabsIntakeToolsSaveIntakePatchRouteImport } from './routes/api/public/elevenlabs/intake/tools/save-intake-patch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppJudgeModeRoute = AppJudgeModeRouteImport.update({
  id: '/judge-mode',
  path: '/judge-mode',
  getParentRoute: () => AppRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppNegotiationsIndexRoute = AppNegotiationsIndexRouteImport.update({
  id: '/negotiations/',
  path: '/negotiations/',
  getParentRoute: () => AppRoute,
} as any)
const AppNegotiationsIdRoute = AppNegotiationsIdRouteImport.update({
  id: '/negotiations/$id',
  path: '/negotiations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNegotiationsNewRoute = AppNegotiationsNewRouteImport.update({
  id: '/negotiations/new',
  path: '/negotiations/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicElevenlabsPostCallRoute =
  ApiPublicElevenlabsPostCallRouteImport.update({
    id: '/api/public/elevenlabs/post-call',
    path: '/api/public/elevenlabs/post-call',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppNegotiationsIdCallsRoute = AppNegotiationsIdCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppNegotiationsIdRoute,
} as any)
const AppNegotiationsIdControlRoomRoute =
  AppNegotiationsIdControlRoomRouteImport.update({
    id: '/control-room',
    path: '/control-room',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const AppNegotiationsIdEvidenceRoute =
  AppNegotiationsIdEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const AppNegotiationsIdIntakeRoute = AppNegotiationsIdIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppNegotiationsIdRoute,
} as any)
const AppNegotiationsIdIntegrityRoute =
  AppNegotiationsIdIntegrityRouteImport.update({
    id: '/integrity',
    path: '/integrity',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const AppNegotiationsIdNegotiateRoute =
  AppNegotiationsIdNegotiateRouteImport.update({
    id: '/negotiate',
    path: '/negotiate',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const AppNegotiationsIdOverviewRoute =
  AppNegotiationsIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const AppNegotiationsIdProvidersRoute =
  AppNegotiationsIdProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const AppNegotiationsIdQuotesRoute = AppNegotiationsIdQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppNegotiationsIdRoute,
} as any)
const AppNegotiationsIdReadinessRoute =
  AppNegotiationsIdReadinessRouteImport.update({
    id: '/readiness',
    path: '/readiness',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const AppNegotiationsIdReportRoute = AppNegotiationsIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppNegotiationsIdRoute,
} as any)
const AppNegotiationsIdSpecificationRoute =
  AppNegotiationsIdSpecificationRouteImport.update({
    id: '/specification',
    path: '/specification',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const AppNegotiationsIdVoiceIntakeRoute =
  AppNegotiationsIdVoiceIntakeRouteImport.update({
    id: '/voice-intake',
    path: '/voice-intake',
    getParentRoute: () => AppNegotiationsIdRoute,
  } as any)
const ApiPublicElevenlabsIntakePostCallRoute =
  ApiPublicElevenlabsIntakePostCallRouteImport.update({
    id: '/api/public/elevenlabs/intake/post-call',
    path: '/api/public/elevenlabs/intake/post-call',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsToolsFinalizeCallOutcomeRoute =
  ApiPublicElevenlabsToolsFinalizeCallOutcomeRouteImport.update({
    id: '/api/public/elevenlabs/tools/finalize-call-outcome',
    path: '/api/public/elevenlabs/tools/finalize-call-outcome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsToolsLoadCallContextRoute =
  ApiPublicElevenlabsToolsLoadCallContextRouteImport.update({
    id: '/api/public/elevenlabs/tools/load-call-context',
    path: '/api/public/elevenlabs/tools/load-call-context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsToolsSaveQuoteLineItemRoute =
  ApiPublicElevenlabsToolsSaveQuoteLineItemRouteImport.update({
    id: '/api/public/elevenlabs/tools/save-quote-line-item',
    path: '/api/public/elevenlabs/tools/save-quote-line-item',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsToolsSaveQuoteSnapshotRoute =
  ApiPublicElevenlabsToolsSaveQuoteSnapshotRouteImport.update({
    id: '/api/public/elevenlabs/tools/save-quote-snapshot',
    path: '/api/public/elevenlabs/tools/save-quote-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRoute =
  ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRouteImport.update({
    id: '/api/public/elevenlabs/intake/tools/finalize-intake-session',
    path: '/api/public/elevenlabs/intake/tools/finalize-intake-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsIntakeToolsLoadIntakeContextRoute =
  ApiPublicElevenlabsIntakeToolsLoadIntakeContextRouteImport.update({
    id: '/api/public/elevenlabs/intake/tools/load-intake-context',
    path: '/api/public/elevenlabs/intake/tools/load-intake-context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsIntakeToolsSaveIntakePatchRoute =
  ApiPublicElevenlabsIntakeToolsSaveIntakePatchRouteImport.update({
    id: '/api/public/elevenlabs/intake/tools/save-intake-patch',
    path: '/api/public/elevenlabs/intake/tools/save-intake-patch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/judge-mode': typeof AppJudgeModeRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/negotiations/$id': typeof AppNegotiationsIdRouteWithChildren
  '/app/negotiations/new': typeof AppNegotiationsNewRoute
  '/app/negotiations/': typeof AppNegotiationsIndexRoute
  '/api/public/elevenlabs/post-call': typeof ApiPublicElevenlabsPostCallRoute
  '/app/negotiations/$id/calls': typeof AppNegotiationsIdCallsRoute
  '/app/negotiations/$id/control-room': typeof AppNegotiationsIdControlRoomRoute
  '/app/negotiations/$id/evidence': typeof AppNegotiationsIdEvidenceRoute
  '/app/negotiations/$id/intake': typeof AppNegotiationsIdIntakeRoute
  '/app/negotiations/$id/integrity': typeof AppNegotiationsIdIntegrityRoute
  '/app/negotiations/$id/negotiate': typeof AppNegotiationsIdNegotiateRoute
  '/app/negotiations/$id/overview': typeof AppNegotiationsIdOverviewRoute
  '/app/negotiations/$id/providers': typeof AppNegotiationsIdProvidersRoute
  '/app/negotiations/$id/quotes': typeof AppNegotiationsIdQuotesRoute
  '/app/negotiations/$id/readiness': typeof AppNegotiationsIdReadinessRoute
  '/app/negotiations/$id/report': typeof AppNegotiationsIdReportRoute
  '/app/negotiations/$id/specification': typeof AppNegotiationsIdSpecificationRoute
  '/app/negotiations/$id/voice-intake': typeof AppNegotiationsIdVoiceIntakeRoute
  '/api/public/elevenlabs/intake/post-call': typeof ApiPublicElevenlabsIntakePostCallRoute
  '/api/public/elevenlabs/tools/finalize-call-outcome': typeof ApiPublicElevenlabsToolsFinalizeCallOutcomeRoute
  '/api/public/elevenlabs/tools/load-call-context': typeof ApiPublicElevenlabsToolsLoadCallContextRoute
  '/api/public/elevenlabs/tools/save-quote-line-item': typeof ApiPublicElevenlabsToolsSaveQuoteLineItemRoute
  '/api/public/elevenlabs/tools/save-quote-snapshot': typeof ApiPublicElevenlabsToolsSaveQuoteSnapshotRoute
  '/api/public/elevenlabs/intake/tools/finalize-intake-session': typeof ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRoute
  '/api/public/elevenlabs/intake/tools/load-intake-context': typeof ApiPublicElevenlabsIntakeToolsLoadIntakeContextRoute
  '/api/public/elevenlabs/intake/tools/save-intake-patch': typeof ApiPublicElevenlabsIntakeToolsSaveIntakePatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/judge-mode': typeof AppJudgeModeRoute
  '/app': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/negotiations/$id': typeof AppNegotiationsIdRouteWithChildren
  '/app/negotiations/new': typeof AppNegotiationsNewRoute
  '/app/negotiations': typeof AppNegotiationsIndexRoute
  '/api/public/elevenlabs/post-call': typeof ApiPublicElevenlabsPostCallRoute
  '/app/negotiations/$id/calls': typeof AppNegotiationsIdCallsRoute
  '/app/negotiations/$id/control-room': typeof AppNegotiationsIdControlRoomRoute
  '/app/negotiations/$id/evidence': typeof AppNegotiationsIdEvidenceRoute
  '/app/negotiations/$id/intake': typeof AppNegotiationsIdIntakeRoute
  '/app/negotiations/$id/integrity': typeof AppNegotiationsIdIntegrityRoute
  '/app/negotiations/$id/negotiate': typeof AppNegotiationsIdNegotiateRoute
  '/app/negotiations/$id/overview': typeof AppNegotiationsIdOverviewRoute
  '/app/negotiations/$id/providers': typeof AppNegotiationsIdProvidersRoute
  '/app/negotiations/$id/quotes': typeof AppNegotiationsIdQuotesRoute
  '/app/negotiations/$id/readiness': typeof AppNegotiationsIdReadinessRoute
  '/app/negotiations/$id/report': typeof AppNegotiationsIdReportRoute
  '/app/negotiations/$id/specification': typeof AppNegotiationsIdSpecificationRoute
  '/app/negotiations/$id/voice-intake': typeof AppNegotiationsIdVoiceIntakeRoute
  '/api/public/elevenlabs/intake/post-call': typeof ApiPublicElevenlabsIntakePostCallRoute
  '/api/public/elevenlabs/tools/finalize-call-outcome': typeof ApiPublicElevenlabsToolsFinalizeCallOutcomeRoute
  '/api/public/elevenlabs/tools/load-call-context': typeof ApiPublicElevenlabsToolsLoadCallContextRoute
  '/api/public/elevenlabs/tools/save-quote-line-item': typeof ApiPublicElevenlabsToolsSaveQuoteLineItemRoute
  '/api/public/elevenlabs/tools/save-quote-snapshot': typeof ApiPublicElevenlabsToolsSaveQuoteSnapshotRoute
  '/api/public/elevenlabs/intake/tools/finalize-intake-session': typeof ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRoute
  '/api/public/elevenlabs/intake/tools/load-intake-context': typeof ApiPublicElevenlabsIntakeToolsLoadIntakeContextRoute
  '/api/public/elevenlabs/intake/tools/save-intake-patch': typeof ApiPublicElevenlabsIntakeToolsSaveIntakePatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/judge-mode': typeof AppJudgeModeRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/negotiations/$id': typeof AppNegotiationsIdRouteWithChildren
  '/app/negotiations/new': typeof AppNegotiationsNewRoute
  '/app/negotiations/': typeof AppNegotiationsIndexRoute
  '/api/public/elevenlabs/post-call': typeof ApiPublicElevenlabsPostCallRoute
  '/app/negotiations/$id/calls': typeof AppNegotiationsIdCallsRoute
  '/app/negotiations/$id/control-room': typeof AppNegotiationsIdControlRoomRoute
  '/app/negotiations/$id/evidence': typeof AppNegotiationsIdEvidenceRoute
  '/app/negotiations/$id/intake': typeof AppNegotiationsIdIntakeRoute
  '/app/negotiations/$id/integrity': typeof AppNegotiationsIdIntegrityRoute
  '/app/negotiations/$id/negotiate': typeof AppNegotiationsIdNegotiateRoute
  '/app/negotiations/$id/overview': typeof AppNegotiationsIdOverviewRoute
  '/app/negotiations/$id/providers': typeof AppNegotiationsIdProvidersRoute
  '/app/negotiations/$id/quotes': typeof AppNegotiationsIdQuotesRoute
  '/app/negotiations/$id/readiness': typeof AppNegotiationsIdReadinessRoute
  '/app/negotiations/$id/report': typeof AppNegotiationsIdReportRoute
  '/app/negotiations/$id/specification': typeof AppNegotiationsIdSpecificationRoute
  '/app/negotiations/$id/voice-intake': typeof AppNegotiationsIdVoiceIntakeRoute
  '/api/public/elevenlabs/intake/post-call': typeof ApiPublicElevenlabsIntakePostCallRoute
  '/api/public/elevenlabs/tools/finalize-call-outcome': typeof ApiPublicElevenlabsToolsFinalizeCallOutcomeRoute
  '/api/public/elevenlabs/tools/load-call-context': typeof ApiPublicElevenlabsToolsLoadCallContextRoute
  '/api/public/elevenlabs/tools/save-quote-line-item': typeof ApiPublicElevenlabsToolsSaveQuoteLineItemRoute
  '/api/public/elevenlabs/tools/save-quote-snapshot': typeof ApiPublicElevenlabsToolsSaveQuoteSnapshotRoute
  '/api/public/elevenlabs/intake/tools/finalize-intake-session': typeof ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRoute
  '/api/public/elevenlabs/intake/tools/load-intake-context': typeof ApiPublicElevenlabsIntakeToolsLoadIntakeContextRoute
  '/api/public/elevenlabs/intake/tools/save-intake-patch': typeof ApiPublicElevenlabsIntakeToolsSaveIntakePatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/architecture'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/judge-mode'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/negotiations/$id'
    | '/app/negotiations/new'
    | '/app/negotiations/'
    | '/api/public/elevenlabs/post-call'
    | '/app/negotiations/$id/calls'
    | '/app/negotiations/$id/control-room'
    | '/app/negotiations/$id/evidence'
    | '/app/negotiations/$id/intake'
    | '/app/negotiations/$id/integrity'
    | '/app/negotiations/$id/negotiate'
    | '/app/negotiations/$id/overview'
    | '/app/negotiations/$id/providers'
    | '/app/negotiations/$id/quotes'
    | '/app/negotiations/$id/readiness'
    | '/app/negotiations/$id/report'
    | '/app/negotiations/$id/specification'
    | '/app/negotiations/$id/voice-intake'
    | '/api/public/elevenlabs/intake/post-call'
    | '/api/public/elevenlabs/tools/finalize-call-outcome'
    | '/api/public/elevenlabs/tools/load-call-context'
    | '/api/public/elevenlabs/tools/save-quote-line-item'
    | '/api/public/elevenlabs/tools/save-quote-snapshot'
    | '/api/public/elevenlabs/intake/tools/finalize-intake-session'
    | '/api/public/elevenlabs/intake/tools/load-intake-context'
    | '/api/public/elevenlabs/intake/tools/save-intake-patch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/judge-mode'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/negotiations/$id'
    | '/app/negotiations/new'
    | '/app/negotiations'
    | '/api/public/elevenlabs/post-call'
    | '/app/negotiations/$id/calls'
    | '/app/negotiations/$id/control-room'
    | '/app/negotiations/$id/evidence'
    | '/app/negotiations/$id/intake'
    | '/app/negotiations/$id/integrity'
    | '/app/negotiations/$id/negotiate'
    | '/app/negotiations/$id/overview'
    | '/app/negotiations/$id/providers'
    | '/app/negotiations/$id/quotes'
    | '/app/negotiations/$id/readiness'
    | '/app/negotiations/$id/report'
    | '/app/negotiations/$id/specification'
    | '/app/negotiations/$id/voice-intake'
    | '/api/public/elevenlabs/intake/post-call'
    | '/api/public/elevenlabs/tools/finalize-call-outcome'
    | '/api/public/elevenlabs/tools/load-call-context'
    | '/api/public/elevenlabs/tools/save-quote-line-item'
    | '/api/public/elevenlabs/tools/save-quote-snapshot'
    | '/api/public/elevenlabs/intake/tools/finalize-intake-session'
    | '/api/public/elevenlabs/intake/tools/load-intake-context'
    | '/api/public/elevenlabs/intake/tools/save-intake-patch'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/architecture'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/judge-mode'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/negotiations/$id'
    | '/app/negotiations/new'
    | '/app/negotiations/'
    | '/api/public/elevenlabs/post-call'
    | '/app/negotiations/$id/calls'
    | '/app/negotiations/$id/control-room'
    | '/app/negotiations/$id/evidence'
    | '/app/negotiations/$id/intake'
    | '/app/negotiations/$id/integrity'
    | '/app/negotiations/$id/negotiate'
    | '/app/negotiations/$id/overview'
    | '/app/negotiations/$id/providers'
    | '/app/negotiations/$id/quotes'
    | '/app/negotiations/$id/readiness'
    | '/app/negotiations/$id/report'
    | '/app/negotiations/$id/specification'
    | '/app/negotiations/$id/voice-intake'
    | '/api/public/elevenlabs/intake/post-call'
    | '/api/public/elevenlabs/tools/finalize-call-outcome'
    | '/api/public/elevenlabs/tools/load-call-context'
    | '/api/public/elevenlabs/tools/save-quote-line-item'
    | '/api/public/elevenlabs/tools/save-quote-snapshot'
    | '/api/public/elevenlabs/intake/tools/finalize-intake-session'
    | '/api/public/elevenlabs/intake/tools/load-intake-context'
    | '/api/public/elevenlabs/intake/tools/save-intake-patch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicElevenlabsPostCallRoute: typeof ApiPublicElevenlabsPostCallRoute
  ApiPublicElevenlabsIntakePostCallRoute: typeof ApiPublicElevenlabsIntakePostCallRoute
  ApiPublicElevenlabsToolsFinalizeCallOutcomeRoute: typeof ApiPublicElevenlabsToolsFinalizeCallOutcomeRoute
  ApiPublicElevenlabsToolsLoadCallContextRoute: typeof ApiPublicElevenlabsToolsLoadCallContextRoute
  ApiPublicElevenlabsToolsSaveQuoteLineItemRoute: typeof ApiPublicElevenlabsToolsSaveQuoteLineItemRoute
  ApiPublicElevenlabsToolsSaveQuoteSnapshotRoute: typeof ApiPublicElevenlabsToolsSaveQuoteSnapshotRoute
  ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRoute: typeof ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRoute
  ApiPublicElevenlabsIntakeToolsLoadIntakeContextRoute: typeof ApiPublicElevenlabsIntakeToolsLoadIntakeContextRoute
  ApiPublicElevenlabsIntakeToolsSaveIntakePatchRoute: typeof ApiPublicElevenlabsIntakeToolsSaveIntakePatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/judge-mode': {
      id: '/app/judge-mode'
      path: '/judge-mode'
      fullPath: '/app/judge-mode'
      preLoaderRoute: typeof AppJudgeModeRouteImport
      parentRoute: typeof AppRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/negotiations/': {
      id: '/app/negotiations/'
      path: '/negotiations'
      fullPath: '/app/negotiations/'
      preLoaderRoute: typeof AppNegotiationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/negotiations/$id': {
      id: '/app/negotiations/$id'
      path: '/negotiations/$id'
      fullPath: '/app/negotiations/$id'
      preLoaderRoute: typeof AppNegotiationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/negotiations/new': {
      id: '/app/negotiations/new'
      path: '/negotiations/new'
      fullPath: '/app/negotiations/new'
      preLoaderRoute: typeof AppNegotiationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/elevenlabs/post-call': {
      id: '/api/public/elevenlabs/post-call'
      path: '/api/public/elevenlabs/post-call'
      fullPath: '/api/public/elevenlabs/post-call'
      preLoaderRoute: typeof ApiPublicElevenlabsPostCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/negotiations/$id/calls': {
      id: '/app/negotiations/$id/calls'
      path: '/calls'
      fullPath: '/app/negotiations/$id/calls'
      preLoaderRoute: typeof AppNegotiationsIdCallsRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/control-room': {
      id: '/app/negotiations/$id/control-room'
      path: '/control-room'
      fullPath: '/app/negotiations/$id/control-room'
      preLoaderRoute: typeof AppNegotiationsIdControlRoomRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/evidence': {
      id: '/app/negotiations/$id/evidence'
      path: '/evidence'
      fullPath: '/app/negotiations/$id/evidence'
      preLoaderRoute: typeof AppNegotiationsIdEvidenceRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/intake': {
      id: '/app/negotiations/$id/intake'
      path: '/intake'
      fullPath: '/app/negotiations/$id/intake'
      preLoaderRoute: typeof AppNegotiationsIdIntakeRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/integrity': {
      id: '/app/negotiations/$id/integrity'
      path: '/integrity'
      fullPath: '/app/negotiations/$id/integrity'
      preLoaderRoute: typeof AppNegotiationsIdIntegrityRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/negotiate': {
      id: '/app/negotiations/$id/negotiate'
      path: '/negotiate'
      fullPath: '/app/negotiations/$id/negotiate'
      preLoaderRoute: typeof AppNegotiationsIdNegotiateRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/overview': {
      id: '/app/negotiations/$id/overview'
      path: '/overview'
      fullPath: '/app/negotiations/$id/overview'
      preLoaderRoute: typeof AppNegotiationsIdOverviewRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/providers': {
      id: '/app/negotiations/$id/providers'
      path: '/providers'
      fullPath: '/app/negotiations/$id/providers'
      preLoaderRoute: typeof AppNegotiationsIdProvidersRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/quotes': {
      id: '/app/negotiations/$id/quotes'
      path: '/quotes'
      fullPath: '/app/negotiations/$id/quotes'
      preLoaderRoute: typeof AppNegotiationsIdQuotesRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/readiness': {
      id: '/app/negotiations/$id/readiness'
      path: '/readiness'
      fullPath: '/app/negotiations/$id/readiness'
      preLoaderRoute: typeof AppNegotiationsIdReadinessRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/report': {
      id: '/app/negotiations/$id/report'
      path: '/report'
      fullPath: '/app/negotiations/$id/report'
      preLoaderRoute: typeof AppNegotiationsIdReportRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/specification': {
      id: '/app/negotiations/$id/specification'
      path: '/specification'
      fullPath: '/app/negotiations/$id/specification'
      preLoaderRoute: typeof AppNegotiationsIdSpecificationRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/app/negotiations/$id/voice-intake': {
      id: '/app/negotiations/$id/voice-intake'
      path: '/voice-intake'
      fullPath: '/app/negotiations/$id/voice-intake'
      preLoaderRoute: typeof AppNegotiationsIdVoiceIntakeRouteImport
      parentRoute: typeof AppNegotiationsIdRoute
    }
    '/api/public/elevenlabs/intake/post-call': {
      id: '/api/public/elevenlabs/intake/post-call'
      path: '/api/public/elevenlabs/intake/post-call'
      fullPath: '/api/public/elevenlabs/intake/post-call'
      preLoaderRoute: typeof ApiPublicElevenlabsIntakePostCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/tools/finalize-call-outcome': {
      id: '/api/public/elevenlabs/tools/finalize-call-outcome'
      path: '/api/public/elevenlabs/tools/finalize-call-outcome'
      fullPath: '/api/public/elevenlabs/tools/finalize-call-outcome'
      preLoaderRoute: typeof ApiPublicElevenlabsToolsFinalizeCallOutcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/tools/load-call-context': {
      id: '/api/public/elevenlabs/tools/load-call-context'
      path: '/api/public/elevenlabs/tools/load-call-context'
      fullPath: '/api/public/elevenlabs/tools/load-call-context'
      preLoaderRoute: typeof ApiPublicElevenlabsToolsLoadCallContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/tools/save-quote-line-item': {
      id: '/api/public/elevenlabs/tools/save-quote-line-item'
      path: '/api/public/elevenlabs/tools/save-quote-line-item'
      fullPath: '/api/public/elevenlabs/tools/save-quote-line-item'
      preLoaderRoute: typeof ApiPublicElevenlabsToolsSaveQuoteLineItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/tools/save-quote-snapshot': {
      id: '/api/public/elevenlabs/tools/save-quote-snapshot'
      path: '/api/public/elevenlabs/tools/save-quote-snapshot'
      fullPath: '/api/public/elevenlabs/tools/save-quote-snapshot'
      preLoaderRoute: typeof ApiPublicElevenlabsToolsSaveQuoteSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/intake/tools/finalize-intake-session': {
      id: '/api/public/elevenlabs/intake/tools/finalize-intake-session'
      path: '/api/public/elevenlabs/intake/tools/finalize-intake-session'
      fullPath: '/api/public/elevenlabs/intake/tools/finalize-intake-session'
      preLoaderRoute: typeof ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/intake/tools/load-intake-context': {
      id: '/api/public/elevenlabs/intake/tools/load-intake-context'
      path: '/api/public/elevenlabs/intake/tools/load-intake-context'
      fullPath: '/api/public/elevenlabs/intake/tools/load-intake-context'
      preLoaderRoute: typeof ApiPublicElevenlabsIntakeToolsLoadIntakeContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/intake/tools/save-intake-patch': {
      id: '/api/public/elevenlabs/intake/tools/save-intake-patch'
      path: '/api/public/elevenlabs/intake/tools/save-intake-patch'
      fullPath: '/api/public/elevenlabs/intake/tools/save-intake-patch'
      preLoaderRoute: typeof ApiPublicElevenlabsIntakeToolsSaveIntakePatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppNegotiationsIdRouteChildren {
  AppNegotiationsIdCallsRoute: typeof AppNegotiationsIdCallsRoute
  AppNegotiationsIdControlRoomRoute: typeof AppNegotiationsIdControlRoomRoute
  AppNegotiationsIdEvidenceRoute: typeof AppNegotiationsIdEvidenceRoute
  AppNegotiationsIdIntakeRoute: typeof AppNegotiationsIdIntakeRoute
  AppNegotiationsIdIntegrityRoute: typeof AppNegotiationsIdIntegrityRoute
  AppNegotiationsIdNegotiateRoute: typeof AppNegotiationsIdNegotiateRoute
  AppNegotiationsIdOverviewRoute: typeof AppNegotiationsIdOverviewRoute
  AppNegotiationsIdProvidersRoute: typeof AppNegotiationsIdProvidersRoute
  AppNegotiationsIdQuotesRoute: typeof AppNegotiationsIdQuotesRoute
  AppNegotiationsIdReadinessRoute: typeof AppNegotiationsIdReadinessRoute
  AppNegotiationsIdReportRoute: typeof AppNegotiationsIdReportRoute
  AppNegotiationsIdSpecificationRoute: typeof AppNegotiationsIdSpecificationRoute
  AppNegotiationsIdVoiceIntakeRoute: typeof AppNegotiationsIdVoiceIntakeRoute
}

const AppNegotiationsIdRouteChildren: AppNegotiationsIdRouteChildren = {
  AppNegotiationsIdCallsRoute: AppNegotiationsIdCallsRoute,
  AppNegotiationsIdControlRoomRoute: AppNegotiationsIdControlRoomRoute,
  AppNegotiationsIdEvidenceRoute: AppNegotiationsIdEvidenceRoute,
  AppNegotiationsIdIntakeRoute: AppNegotiationsIdIntakeRoute,
  AppNegotiationsIdIntegrityRoute: AppNegotiationsIdIntegrityRoute,
  AppNegotiationsIdNegotiateRoute: AppNegotiationsIdNegotiateRoute,
  AppNegotiationsIdOverviewRoute: AppNegotiationsIdOverviewRoute,
  AppNegotiationsIdProvidersRoute: AppNegotiationsIdProvidersRoute,
  AppNegotiationsIdQuotesRoute: AppNegotiationsIdQuotesRoute,
  AppNegotiationsIdReadinessRoute: AppNegotiationsIdReadinessRoute,
  AppNegotiationsIdReportRoute: AppNegotiationsIdReportRoute,
  AppNegotiationsIdSpecificationRoute: AppNegotiationsIdSpecificationRoute,
  AppNegotiationsIdVoiceIntakeRoute: AppNegotiationsIdVoiceIntakeRoute,
}

const AppNegotiationsIdRouteWithChildren =
  AppNegotiationsIdRoute._addFileChildren(AppNegotiationsIdRouteChildren)

interface AppRouteChildren {
  AppJudgeModeRoute: typeof AppJudgeModeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNegotiationsIdRoute: typeof AppNegotiationsIdRouteWithChildren
  AppNegotiationsNewRoute: typeof AppNegotiationsNewRoute
  AppNegotiationsIndexRoute: typeof AppNegotiationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppJudgeModeRoute: AppJudgeModeRoute,
  AppIndexRoute: AppIndexRoute,
  AppNegotiationsIdRoute: AppNegotiationsIdRouteWithChildren,
  AppNegotiationsNewRoute: AppNegotiationsNewRoute,
  AppNegotiationsIndexRoute: AppNegotiationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicElevenlabsPostCallRoute: ApiPublicElevenlabsPostCallRoute,
  ApiPublicElevenlabsIntakePostCallRoute:
    ApiPublicElevenlabsIntakePostCallRoute,
  ApiPublicElevenlabsToolsFinalizeCallOutcomeRoute:
    ApiPublicElevenlabsToolsFinalizeCallOutcomeRoute,
  ApiPublicElevenlabsToolsLoadCallContextRoute:
    ApiPublicElevenlabsToolsLoadCallContextRoute,
  ApiPublicElevenlabsToolsSaveQuoteLineItemRoute:
    ApiPublicElevenlabsToolsSaveQuoteLineItemRoute,
  ApiPublicElevenlabsToolsSaveQuoteSnapshotRoute:
    ApiPublicElevenlabsToolsSaveQuoteSnapshotRoute,
  ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRoute:
    ApiPublicElevenlabsIntakeToolsFinalizeIntakeSessionRoute,
  ApiPublicElevenlabsIntakeToolsLoadIntakeContextRoute:
    ApiPublicElevenlabsIntakeToolsLoadIntakeContextRoute,
  ApiPublicElevenlabsIntakeToolsSaveIntakePatchRoute:
    ApiPublicElevenlabsIntakeToolsSaveIntakePatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
